# fly.toml app configuration file generated for unbrewed-v2 on 2023-12-11T19:17:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unbrewed-v2"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
=======
app = "ubrewed"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "dfw"
processes = []

[build]
dockerfile = "Dockerfile.gameserver"

[deploy]
strategy = "rolling"

[env]

# Should set this up!
#[[statics]]
#  guest_path = "/app/public"
#  url_prefix = "/public"

# Might be nice to add metrics later
#[metrics]
#port = 9091       # default for most prometheus clients
#path = "/metrics" # default for most prometheus clients

[[services]]
internal_port = 1111
processes = ["app"]
protocol = "tcp"
#[services.concurrency]
#hard_limit = 25
#soft_limit = 20
#type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
