// AUTO-GENERATED by lib/buildTools/generateChangelogIndex.js — do not edit by hand.
// Regenerated on every next.config.js load (next dev, next build, jest via next/jest).
import type { ChangelogEntry } from "./types";

import entry0 from "../../content/changelog/2026-09-09-leon-s-kennedy.json";
import entry1 from "../../content/changelog/2026-09-14-irl-mode.json";
import entry2 from "../../content/changelog/2026-09-27-stats-dashboard.json";
import entry3 from "../../content/changelog/2026-09-27-tabletop-view.json";

// Cast needed: JSON imports infer `tags` as string[], not ChangelogTag[].
// entries.ts validates the real shape at runtime.
export const rawChangelogEntries = [entry0, entry1, entry2, entry3] as ChangelogEntry[];
