/**
 * The changelog entry format. One JSON file per entry lives under
 * `content/changelog/<id>.json` (see `generatedEntries.ts`, regenerated by
 * `next.config.js` on every `next dev` / `next build` / jest run) and is
 * loaded + validated by `getChangelogEntries()` in `entries.ts`.
 */
export type ChangelogTag = "deck" | "feature" | "fix";

export type ChangelogEntry = {
  /** "<yyyy-mm-dd>-<kebab-slug>", unique; sorts by date as a plain string. */
  id: string;
  /** "yyyy-mm-dd"; must match the date prefix of `id`. */
  date: string;
  title: string;
  /** 1-2 sentences; used by the card, the dialog and the page. */
  summary: string;
  /** Optional extra paragraphs, shown only on /changelog. */
  body?: string[];
  tags: ChangelogTag[];
  /** Shows the "Pro" label. */
  pro?: boolean;
  /** Only highlight entries may open the update dialog. */
  highlight: boolean;
  video?: { slug: string };
  /** Internal route. */
  cta?: { label: string; href: string };
};
