import Head from "next/head";

export const DocumentHeader = () => {
  return (
    <Head>
      <title>Unbrewed - P2P</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scaleable=0"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
