import Head from "next/head";

export const DocumentHeader = () => {
  return (
    <Head>
      <title>Unbrewed - P2P</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scaleable=0"
      />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link
        href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;700&display=swap"
        rel="stylesheet"
      ></link>
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
