/**
 * Regenerates `lib/changelog/generatedEntries.ts` from the one-file-per-entry
 * content under `content/changelog/*.json` (unbrewed-p2p-982).
 *
 * Adding a changelog entry means adding exactly one JSON file — no index to
 * hand-edit. This writes the index as static imports (rather than a
 * webpack-only `require.context`) so it works identically under `next dev`,
 * `next build && next export`, and jest.
 *
 * Called from `next.config.js`, which runs on every one of those — `next
 * dev`/`next build` load it directly, and `next/jest` loads it too (it reads
 * env/config via Next's `loadConfig`) — so the generated file is always fresh
 * before anything imports it.
 */
const fs = require("fs");
const path = require("path");

const CONTENT_DIR = path.join(__dirname, "..", "..", "content", "changelog");
const OUT_FILE = path.join(__dirname, "..", "changelog", "generatedEntries.ts");

function generateChangelogIndex() {
  const files = fs.existsSync(CONTENT_DIR)
    ? fs
        .readdirSync(CONTENT_DIR)
        .filter((f) => f.endsWith(".json"))
        .sort()
    : [];

  const imports = files
    .map((f, i) => `import entry${i} from "../../content/changelog/${f}";`)
    .join("\n");
  const items = files.map((_, i) => `entry${i}`).join(", ");

  const contents = `// AUTO-GENERATED by lib/buildTools/generateChangelogIndex.js — do not edit by hand.
// Regenerated on every next.config.js load (next dev, next build, jest via next/jest).
import type { ChangelogEntry } from "./types";

${imports}

// Cast needed: JSON imports infer \`tags\` as string[], not ChangelogTag[].
// entries.ts validates the real shape at runtime.
export const rawChangelogEntries = [${items}] as ChangelogEntry[];
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, contents);
}

module.exports = { generateChangelogIndex };
