name: Deploy to Fly.io

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "gameserver/**" # only trigger when gameserver files change

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy-fly-io:
    name: "Deploy to Fly.io"
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
